### ISSUE TITLE
template render error : unknown block tag:bilibili

### ISSUE THREAD

**Issue by akarineren** [Z4Tech/hexo-tag-bilibili#2]
**1**
npm install hexo-tag-bilibili
**2**

``` md
title:video
date:2015
tags:

---

<div class="bili_video">
 {% bilibili 3290124 3%}
</div>
```

``` cmd
hexo g
```

Can you tell me how it's going?

**Comment by Z4Tech** [comment]
use `npm install --save hexo-tag-bilibili` instead of `npm install hexo-tag-bilibili`

By the way, there is no need for you to wrap it with div `bili_video`, such div is already included in the template. Also, you only need av_id for this video since it don't have multiple pages. `{% bilibili 3290124 %}`

**Comment by akarineren** [comment]
nice!
